spring.application.name=greenhouse-core
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/greenflow
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=greenhouse-core
spring.kafka.consumer.auto-offset-reset=earliest

# Topics
sensor.kafka.topic=sensor-readings

# JPA
spring.jpa.open-in-view=false
