spring.application.name=sensor-service
server.port=8085
# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Topic
sensor.kafka.topic=sensor-readings
sensor.scheduler.fixed-rate-ms=10000

# Console logging
logging.level.com.GreenFlow.sensor_service=INFO

jwt.secret=greenflow-super-secret-key-please-change-in-production-2026
